### ISSUE TITLE
Creating a Release/Tag

### ISSUE THREAD

**Issue by ademirfranciscosilva** [vavrecan/exp4php#1]
Please consider creating a version or branch, eg 1.0, to make it clear that it is a reliable / stable release.

In this way instead of using:
"vavrecan / exp4php ":" dev-master "
We can use:
"vavrecan / exp4php ":." 1.0 \* " for example.

Thanks in advance!

**Comment by vavrecan** [comment]
thank you - I created branch 1.0 
I use current git version in production without problems so far, but I would like to update it in near future

**Comment by ademirfranciscosilva** [comment]
Thanks Vavrecan!
